graphql: extend type Query trigger this error:
[INFO] [default] compiling...
[ERROR] ✖︎ After transforms, the operation `EvelogFlowsLinesPaginationQuery` that would be sent to the server is empty. Relay is not setup to handle such queries. This is likely due to only querying for client extension fields or `@skip`/`@include` directives with constant values that remove
all selections.

  opencti-front/src/private/components/layer4/evelog_flows/EvelogFlowsLines.js:104:9
  103 │
  104 │   query EvelogFlowsLinesPaginationQuery(
      │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  105 │     $types: [String]

[ERROR] Compilation failed.